[package]
name = "te-shader-play"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.18.0"
winit = { version = "0.29.3", features = ["rwh_05"] }
pollster = "0.3"
imgui = { version = "0.11", features = ["docking"] }
imgui-winit-support = "0.11"
imgui-wgpu = "0.24"
mint = "0.5.9"

[patch.crates-io]
imgui = { git = "https://github.com/Calcoph/imgui-rs", branch = "uptodate-winit" }
imgui-winit-support = { git = "https://github.com/Calcoph/imgui-rs", branch = "uptodate-winit" }
imgui-wgpu = { git = "https://github.com/Calcoph/imgui-wgpu-rs", rev = "53abff5" }
