[package]
name = "te-shader-play"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.18.0"
winit = { version = "0.29.3", features = ["rwh_05"] }
pollster = "0.3"
